# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- BottomDrawerMiguelBranch

pool:
  vmImage: ubuntu-latest
steps:
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'BottomDrawer/**/*.csproj'
    versioningScheme: 'off'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'PublicNugetBenjamin'
