# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- BottomDrawerMiguelBranch

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: BottomDrawer/**/*.csproj
    versioningScheme: byEnvVar
    versionEnvVar: nupkgVersion
- task: DotNetCoreCLI@2
  displayName: 'dotnet push'
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'PublicNugetBenjamin'
  enabled: false
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: external
    publishFeedCredentials: 'PublicNugetBenjamin'