# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- BottomDrawerMiguelBranch

variables:
  buildConfiguration: 'Release'
pool:
  vmImage: ubuntu-latest
steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    #projects: '**/*.csproj'
    projects: 'BottomDrawer/**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: BottomDrawer/**/*.csproj
    nobuild: true
    verbosityPack: 'Normal'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'PublicNugetBenjamin'
    nugetConfigPath: '$(Build.WorkingDirectory)/NuGet.config'
    allowPackageConflicts: true
